### PR TITLE
Easy ndim loops

### PR DESCRIPTION
**Pull request by akaeba**
Initial draft of python module to allow n-dimensional parameter sweeps.

### CODE REVIEW

**Comment by nunobrum** [comment]
Hi Andreas,

thank you very much for your contribution. I must say I like your coding style.
I have however some recommendations in regards to the implementation in Python.
In Python all iterations are done using an iterator object.  Here is an example:
[https://wiki.python.org/moin/Iterator](https://wiki.python.org/moin/Iterator)

Basically instead of having array of indexes, you could have an array of iterators. You only need to catch the StopIteration exception to invoke the __next__ of the next iterator on the vector.
This simplifies the code a lot, and allows you to receive as arguments any time of iterable, not only lists .   

Secondly, I think we need to keep the sweep and sweep_log generators out of the class you have created. The idea is that you can use them as arguments to your add(name, iterator) function.

I'm also thinking ahead towards the integration with the SimManager class. I have added the possibility to add a dictionary on a set_components(...) function that can set multiple components at the same time.
I think it would make sense that the iterator would receive as argument the SimManager and would keep a reference to it. 
This would allow to verify at each add(...) if the component is valid. And another aspect, we should foresee to offer the possibility to aslo iterate parameters or other simulation commands.

I have some ideas, but I think I've already imposed too much. Looking forward to hear your thoughts one this.

I'm really pleased that you are cooperating on this, and I hope the fact I don't accept yet this pull doesn't put you off too much.

**Comment by akaeba** [comment]
>  I think we need to keep the sweep and sweep_log generators out of the class you have created
[Done](https://github.com/akaeba/PyLTSpice/commit/6543369998b43265f44cb2e91a8ce0d14ce7733d)

**Comment by akaeba** [comment]
Okay, I'll try with the iterator ;)

**Comment by nunobrum** [comment]
I've made a few tests yesterday with iterators to make sure the idea works.  So, here are some hints.
In order to create an Iterator out of any iterable object, use the function iter( )

`iterator = iter(<any iterable object>)`

For obtaining the next value out an iterator use __next()__ and you need to capture the StopIteration exception.
Here is a snippet that looks promising.

```
iter_no = 0
iterators = [iter(step.iter) for step in self.iter_list]  # Initialize the iterators
while iter_no >= 0:
    while 0 <= iter_no < n_dim:
        try:
            value = iterators[iter_no].__next__()  # ask for a new value
            iter_no += 1
        except StopIteration:
            iterators[iter_no] = iter(self.iter_list[iter_no].iter)  # At the end of the sweep, initialize the iterator
            iter_no -= 1  # update the previous 
            continue
        # TODO: setting the parameter / value / model / etc....
    if iter_no >= 0:
        # TODO: running the simulation here
        iter_no = n_dim - 1 # Still didn't reach the end, 

```

**Comment by akaeba** [comment]
Do you suggest this code example for inside or outside the iterator module? If it's outside then it can be strong to handle. If I ask a colleague of my (electronic designer, no python guru 😉) he would say that's a lot code to sweep some Params.

**Comment by nunobrum** [comment]
This would be inside the iterator module. In the outside the code would be more or less as you suggested. 
Here is an example of it's usage
```
        Stepper = SimStepper("my_circuit.asc")
        Stepper.add_model_sweep('D1', "BAT54", "BAT46WJ")
        Stepper.add_component_sweep('R1', sweep(2.2, 2,4, 0.2))  # Steps from 2.2 to 2.4 with 0.2 increments
        Stepper.add_parameter_sweep('temp', sweep(0, 80, 20))  # Makes temperature step from 0 to 80 degrees in 20 degree steps
        Stepper.add_component_sweep('R2', (10, 25, 32)) #  Updates the resistor R2 value to be 3.3k
        Stepper.run_all()
```
Meanwhile, I've tested the code above and with some fixes it works. 
I'll accept your pull request and then I'll update the code with the code above using iterators.
I'll also be moving some things around so, we can add more functionality later on. 
Based on this I'm thinking about having a class that makes Monte-Carlo and Worst Case Analysis without having to change the Schematic.

**Comment by nunobrum** [comment]
I have pushed a new class called SimStepper that does the iterations. Let me know if it fits what you had in mind.
I have also added a batch_test2.py to test that class

**Comment by akaeba** [comment]
Hi, yes exactly something in that way i had in mind. In consequence can my code from the sweep_iterators removed again, cause it's redundant.

The only point is:
https://github.com/nunobrum/PyLTSpice/blob/fd37ed6cc66c6fe023c72849020505f305621b58/PyLTSpice/sim_stepping.py#L140

If you like to use an python eval function, I dont know how to come with my user code in between.

```python
for i in test:
    mySimData = test.run_next(<nodes_to_extract>)  # let lts spice calc
    myEval(myDataSim)                                                # call custom python data eval function
```
What do you think?

**Comment by nunobrum** [comment]
Hi Andreas,

Sorry for the late reply. I was on holidays last week.
Given the multi-processor nature of the new code, I thought it would make sense that all the post processing would be handled by the callback function that you can pass to the run_all() function.

First you define a function that received as arguments the raw and the log filenames, where you can make all the evals you wish.
```
def processing_data(raw_file, log_file):
    print("Handling the simulation data of %s" % log_file )
```
then calling the run_all as such, 
`Stepper.run_all(callback=processing_data)`
This way the processing is also done with python threading.

The batch_test2.py script on the tests folder shows how this is done.

**Pull request merged**
